
set(ENABLED_GEMS
    Ros2Project
    Atom
    AudioSystem
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    PhysX
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    DiffuseProbeGrid
    Compression
    WarehouseSample
    RosRobotSample
    ROS2
    ImGui
)
